# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Observo < Formula
  desc "CLI for pushing CI test runs, coverage, and live status to Observo"
  homepage "https://github.com/observo-ai/observo-cli"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/observo-ai/observo-cli/releases/download/v0.6.1/observo_0.6.1_darwin_amd64.tar.gz"
      sha256 "cbd8ad88cbb826e1fd7e043e4278f723776c6de08fa9b9868ff66c28483052db"

      define_method(:install) do
        bin.install "observo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/observo-ai/observo-cli/releases/download/v0.6.1/observo_0.6.1_darwin_arm64.tar.gz"
      sha256 "83216e163e63bd3316bd0d078674435ecd1c68e4062046222a3dd09da441ffa6"

      define_method(:install) do
        bin.install "observo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/observo-ai/observo-cli/releases/download/v0.6.1/observo_0.6.1_linux_amd64.tar.gz"
      sha256 "934dd4086161d1617440e6da02073731a675a61ac7d1ca4ecc52920ccad1841f"
      define_method(:install) do
        bin.install "observo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/observo-ai/observo-cli/releases/download/v0.6.1/observo_0.6.1_linux_arm64.tar.gz"
      sha256 "c0c5e4de7a861b9362ef146990b77e761608ded4904944c0f89472c9bb257816"
      define_method(:install) do
        bin.install "observo"
      end
    end
  end

  test do
    system "#{bin}/observo --version"
  end
end
